name: Hola Mundo
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  hola-mundo:
    name: Hola Mundo
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4
      - name: Ejecutar index.js
        run: node index.js